### ISSUE TITLE
DAO membership fee transfer is not transferred but reserved

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-beta#288] opened 2022-01-19 22:06 UTC
**Describe the bug**
Creating a DAO with the setting "Fee Model = transfer" does reserve the fee on the joiners wallet when joining but should transfer the fee to the DAO treasury.

**To Reproduce**
1. Create a DAO with setting "Fee Model = transfer" and enter a number (eg. 1)
2. choose another wallet than controller or treasury wallet and check your balances
3. check the balances of the DAO treasury ( and the controller - just to be sure)
4. Join the DAO with that wallet 
5. See that the fee is "reserved" in your wallet and not transferred to the DAO treasury

**Expected behavior**
When selecting fee model "transfer" the DAO treasury should get the fee from the user.

**Screenshots**

**Additional context**

**Comment by 2075** [comment] 2022-01-20 13:48
possibly the values are mixed up:
```
 			match &config.fee_model {
 				ControlFeeModel::NoFees => {
 				},
 				ControlFeeModel::Reserve => {
					<balances::Module<T>>::reserve(&account, config.fee)?;
 				},
 				ControlFeeModel::Transfer => {
					let treasury = BodyTreasury::<T>::get(hash);
					let transfer = <balances::Module<T> as Currency<_>>::transfer(
						&account,
						&treasury,
						config.fee,
						ExistenceRequirement::AllowDeath
					);
 				},
 				_ => {}
 			}
```

can you try what happens, when you select reserve?

**Comment by 2075** [comment] 2022-01-20 13:52
@5-mark  ah found the bug, updated the dropdown provider:

```
export const dao_fee_model = [
	{ key: '0', text: 'no fees', value: 0 }, // fees are reserved in actor account
	{ key: '1', text: 'reserve', value: 1 }, // fees are paid to treasury
	{ key: '2', text: 'transfer', value: 2 }, // fees are staked and may result in item drops
]
```
fixed in main:
please try again in 10mins.

**Comment by 5-mark** [comment] 2022-01-20 19:50
@2075 just tried again. but still same behaviour. Setting transfer as fee model but seeing the fee reserved. 
How comes this bug was fixed? it is still in the buglog and not in review. Also I didnt see any pull request?

**Comment by 2075** [comment] 2022-01-20 21:23
i just updated the three values in the main branch. if you can see the three values as shown above, the correct fee calculation should apply.

**Comment by 2075** [comment] 2022-01-24 18:13
please verify @5-mark @soundyogi

**Comment by soundyogi** [comment] 2022-01-24 19:13
testing.

**Comment by 2075** [comment] 2022-01-25 08:36
@soundyogi

**Comment by 2075** [comment] 2022-01-25 08:36
@5-mark

**Comment by 2075** [comment] 2022-01-25 17:12
> testing.

any results @soundyogi ?

**Comment by soundyogi** [comment] 2022-01-25 18:41
- [x] Create a DAO with setting "Fee Model = transfer" and enter a number (eg. 1)
- [x] choose another wallet than controller or treasury wallet and check your balances
- [x] check the balances of the DAO treasury ( and the controller - just to be sure)
![image](https://user-images.githubusercontent.com/3201046/151038220-d5ff48ed-e0e8-4cef-9000-e8c00de1475b.png)

![image](https://user-images.githubusercontent.com/3201046/151038297-de829a68-74d1-43dd-a8e1-ab3d1c8a17e1.png)

![image](https://user-images.githubusercontent.com/3201046/151038333-52487821-2801-4104-8871-1bb34393da0a.png)

![image](https://user-images.githubusercontent.com/3201046/151038361-cbca58da-230f-4cab-bd6c-c22a2048dfd4.png)

- [x] Join the DAO with that wallet

![image](https://user-images.githubusercontent.com/3201046/151038496-9ff28ec0-e470-4110-9437-db9bccfb7674.png)

**- [] See that the fee is "reserved" in your wallet and not transferred to the DAO treasury**

![image](https://user-images.githubusercontent.com/3201046/151038566-80a0f783-3ae4-42c9-bc78-adee401257dd.png)

![image](https://user-images.githubusercontent.com/3201046/151038653-167dca2b-3d8b-4d9f-b2cb-d2d1917d62ba.png)

![image](https://user-images.githubusercontent.com/3201046/151038687-0f23438b-3126-4c16-95c8-7be24bd8ff69.png)

**Comment by soundyogi** [comment] 2022-01-25 18:49
So it seems to me behavior works as intended.

Fee gets deducted from "Check" account on joining the DAO.
Fee gets send to treasury.
Closing.

**Closed by soundyogi** 2022-01-25 18:49 UTC
Labels: bug

**Comment by soundyogi** [comment] 2022-01-25 19:03
for good measure, the same for reserved variant:

create a DAO with reserve model and fee of 1
![image](https://user-images.githubusercontent.com/3201046/151041460-560ee818-4fbc-4bfa-b7d1-6211a57abf9c.png)

![image](https://user-images.githubusercontent.com/3201046/151041617-224aacf1-31da-4e25-9f08-6af9a5698b98.png)

join organisations using the check account:

now all 3 accounts show 1 token reserved:
![image](https://user-images.githubusercontent.com/3201046/151041984-51905ccb-aa82-4bb0-a2fe-11e18735f610.png)

![image](https://user-images.githubusercontent.com/3201046/151042044-a97008d1-ed88-4fbc-b9e4-358abda10321.png)

![image](https://user-images.githubusercontent.com/3201046/151042098-ccd0221b-8ff5-4cd3-bc63-488f67059d11.png)

**Comment by soundyogi** [comment] 2022-01-25 19:04
@2075 @5-mark is this reserve behavior correct?

**Comment by 2075** [comment] 2022-01-25 19:05
should:

0 = no fees
1 = reserve, no transfer
2 = transfer to treasury

**Comment by soundyogi** [comment] 2022-01-25 19:06
for some reason on all 3 accounts 1 ZERO was reserved - this is what seems odd to me

**Comment by 2075** [comment] 2022-01-25 19:06
hm reserved or maybe tx fees?

**Comment by 2075** [comment] 2022-01-25 19:07
lets move to discord

**Comment by soundyogi** [comment] 2022-01-25 20:02
I can confirm that 1 ZERO gets reserved for each the treasury and the controller when creating a organistions with the reserve fee model.
